var app={},e_screenPoint;
require("dojo/parser dojo/promise/all esri/map esri/geometry/Extent esri/tasks/query esri/tasks/QueryTask esri/layers/FeatureLayer esri/symbols/TextSymbol esri/layers/LabelClass esri/Color esri/tasks/locator esri/dijit/Search esri/dijit/HomeButton esri/dijit/LocateButton dijit/form/ToggleButton dijit/layout/BorderContainer dijit/layout/ContentPane dojo/domReady!".split(" "),function(h,m,n,p,k,f,e,b,d,g,q,r,t,u,v){function w(a){0<a.features.length&&app.map.setExtent(a.features[0].geometry.getExtent())}function l(a){app.qItem1.geometry=
app.qItem2.geometry=a;item1=app.qtItem1.execute(app.qItem1);item2=app.qtItem2.execute(app.qItem2);promises=new m([item1,item2]);promises.then(x)}function x(a){a[0].hasOwnProperty("features")||console.error("Query 1 failed.");a[1].hasOwnProperty("features")||console.error("Query 2 failed.");var c=a[0].features;var b=a[1].features;app.map.graphics.clear();0==c.length||0==b.length?(a="",c="Nothing found - outside Tacoma."):(a="<b>District "+c[0].attributes.District+"</b></div>",c="<div class='esriViewPopup'><div class='mainSection'><a href='"+
c[0].attributes.WebPage+"' target='_blank'>"+c[0].attributes.Councilmem+" - Position "+c[0].attributes.DIST_ID+"</a><br>"+c[0].attributes.Councilm_3+"<br><a href='mailto:"+c[0].attributes.Councilm_1+"' target='_blank'>Email</a><br><br><a href='https://www.cityoftacoma.org/cms/one.aspx?portalId=169&pageId=10289' target='_blank'>Mayor Victoria Woodards</a><br><br><b>At-Large Councilmembers</b><br><a href='https://www.cityoftacoma.org/cms/One.aspx?portalId=169&pageId=70230' target='_blank'>Lillian Hunter, Position 6</a><br><a href='https://www.cityoftacoma.org/cms/One.aspx?portalId=169&pageId=95002' target='_blank'>Deputy Mayor Conor McCarthy, Position 7</a><br><a href='https://www.cityoftacoma.org/cms/One.aspx?portalId=169&pageId=92937' target='_blank'>Kristina Walker, Position 8</a><br><br><b>Support Staff</b><br>"+
c[0].attributes.Councilm_4+"<br><a href='mailto:"+c[0].attributes.Councilm_5+"' target='_blank'>Email</a><br><br><a href='"+b[0].attributes.URL+"' target='_blank'>"+b[0].attributes.Neighborho+"</a></div></div>");500>app.map.height&&app.map.infoWindow.resize(200,230);app.map.infoWindow.setTitle(a);app.map.infoWindow.setContent(c);app.map.infoWindow.show(e_screenPoint)}h.parse();app.map=new n("map",{center:[-122.45,47.25],zoom:12,basemap:"topo",showLabels:!0});h=new r({sources:[{locator:new q("https://gis.cityoftacoma.org/arcgis/rest/services/Locators/Tacoma_Address_Geocoding_Service/GeocodeServer"),
placeholder:"Search by address",singleLineFieldName:"SingleLine",localSearchOptions:{minScale:3E5,distance:5E4}}],map:app.map},"search");h.startup();h.on("select-result",function(a){app.map.infoWindow.hide();e_screenPoint=a.result.feature.geometry;l(a.result.feature.geometry)});new v({title:"Toggle Basemap",onChange:function(a){a?(app.map.setBasemap("hybrid"),this.set("iconClass","dijitButtonNode2")):(app.map.setBasemap("topo"),this.set("iconClass","dijitButtonNode"));document.activeElement.blur()}},
"BasemapToggle");(new t({map:app.map},"HomeButton")).startup();geoLocate=new u({scale:1440,map:app.map},"LocateButton");geoLocate.startup();geoLocate.on("locate",function(a){candidate_location=a.graphic.geometry;e_screenPoint=app.map.toScreen(candidate_location);l(a.graphic.geometry)});e=new e("https://services3.arcgis.com/SCwJH1pD8WSn5T5y/arcgis/rest/services/Tacoma_Councilmanic_District_Query_Layer/FeatureServer/0",{mode:e.MODE_ONDEMAND,outFields:["*"],opacity:.5});g=new g("#666");b=(new b).setColor(g);
b.font.setSize("14pt");b.font.setFamily("arial");d=new d({labelExpressionInfo:{value:"District {DIST_ID}"}});d.symbol=b;e.setLabelingInfo([d]);app.map.addLayer(e);app.qtItem1=new f("https://services3.arcgis.com/SCwJH1pD8WSn5T5y/arcgis/rest/services/Tacoma_Councilmanic_District_Query_Layer/FeatureServer/0");app.qItem1=new k;app.qtItem2=new f("https://services3.arcgis.com/SCwJH1pD8WSn5T5y/arcgis/rest/services/Tacoma_Neighborhood_Council_Districts/FeatureServer/0");app.qItem2=new k;app.qItem1.returnGeometry=
app.qItem2.returnGeometry=!0;app.qItem1.outFields=app.qItem2.outFields=["*"];app.map.on("click",function(a){e_screenPoint=a.screenPoint;point=a.mapPoint;pxWidth=app.map.extent.getWidth()/app.map.width;padding=3*pxWidth;qGeom=new p({xmin:point.x-padding,ymin:point.y-padding,xmax:point.x+padding,ymax:point.y+padding,spatialReference:point.spatialReference});l(qGeom)});gcxAnalytics.configMap(app.map);if(null!=window.location&&1<window.location.search.length){f=window.location.search.substring(1).split("&");
d={};b=0;for(g=f.length;b<g;b++)e=f[b].split("="),d[e[0]]=e[1];void 0!=d.District&&""!=d.District&&(app.qZoomDistrict=new k,app.qZoomDistrict.where="District="+d.District,app.qZoomDistrict.returnGeometry=!0,app.qtItem1.execute(app.qZoomDistrict,w))}});